author_name: Daniel Thorpe
author_url: http://danthorpe.me
module_name: ValueCoding
module_version: 1.3.0
github_url: https://github.com/danthorpe/ValueCoding
readme: README.md
podspec: ValueCoding.podspec

swift_version: 2.2
xcodebuild-arguments: -scheme,ValueCoding-iOS

custom_categories:
  - name: ValueCoding
    children:
    - CodingType
    - ValueCoding
    - SequenceType
