default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan(xcargs: "-derivedDataPath .fastlane/xcodebuild-data -enableCodeCoverage YES", scheme: 'ValueCoding-iOS')
  end

end

platform :mac do
  
  desc "Runs all the tests"
  lane :test do
        scan(xcargs: "-derivedDataPath .fastlane/xcodebuild-data -enableCodeCoverage YES", scheme: 'ValueCoding-OSX')
  end
  
end
