lane :lint do

    swiftLint(
        mode: :lint, 
        config_file: '.swiftlint.yml'
    )
end


platform :ios do

  desc "Runs all the tests"
  lane :test do
    
    scan(
      scheme: "ValueCoding-iOS",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
    
  end

end

platform :mac do
  
  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: "ValueCoding-OSX",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )

  end
  
end
